import {
	Bluetooth,
	Bookmark as BookmarkIcon,
	Calculator,
	Clipboard,
	Code,
	Cpu,
	Download,
	FileText,
	FolderCog,
	FolderOpen,
	FolderPlus,
	Globe,
	Hash,
	Image,
	type LucideIcon,
	Monitor,
	Moon,
	Music,
	Power,
	Search,
	Settings,
	Sun,
	Terminal,
	Video,
	Volume2,
	Wifi,
} from 'lucide-react'

import type { CommandIcon } from '@/commands/types'

export const DEBOUNCE_MS = 300
export const SHORTCUT = 'Super+Space'

export const SYSTEM_ICON_TO_COMMAND_ICON: Record<string, CommandIcon> = {
	download: 'download',
	'file-text': 'file-text',
	image: 'image',
	video: 'video',
	music: 'music',
	monitor: 'monitor',
}

export const ICON_MAP: Record<CommandIcon, LucideIcon> = {
	search: Search,
	calculator: Calculator,
	globe: Globe,
	bookmark: BookmarkIcon,
	clipboard: Clipboard,
	settings: Settings,
	power: Power,
	folder: FolderOpen,
	terminal: Terminal,
	music: Music,
	code: Code,
	file: FileText,
	hash: Hash,
	cpu: Cpu,
	monitor: Monitor,
	wifi: Wifi,
	bluetooth: Bluetooth,
	volume: Volume2,
	sun: Sun,
	moon: Moon,
	download: Download,
	'file-text': FileText,
	image: Image,
	video: Video,
	'folder-plus': FolderPlus,
	'folder-cog': FolderCog,
}
